Showroom/urls.py
from django.urls import path 
from . import views

app_name = 'Showroom'
urlpatterns = [
    path("" , views.brand_list , name ='brand_list'),
    path("<int:profile_id>" , views.brand_detail , name ='brand_detail'),
    path("team/" , views.our_team , name ='our_team'),
    path("Showrooms.html/" , views.showroomss , name ='showroomss'),

]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Showroom.urls"))
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

Showroom/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.

class staff(models.Model):
    name = models.CharField(max_length=50)
    Role = models.CharField(max_length=50 ,null = True )
    image = models.ImageField(null = True , blank = True)
    def __str__(self):
        return self.name


class feature(models.Model):
    name = models.CharField(max_length=150)
    def __str__(self):
        return self.name
    
class showroom(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(null=True , blank= True)
    Location = models.CharField(max_length=50)
    contact = models.EmailField(max_length=254 , null = True)
    Owner = models.CharField( max_length=50)
    Staff = models.ManyToManyField(staff)

    
    def __str__(self):
        return self.name
    
class brand(models.Model):
    name = models.CharField(max_length=50)
    Logo = models.ImageField(null = True , blank = True)
    showrooms = models.ForeignKey(showroom,on_delete=models.CASCADE, null= True)
    def __str__(self):
        return self.name

class Engine_model(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class engine(models.Model):
    name = models.CharField(max_length=50)
    Engine_no = models.CharField(max_length=50,primary_key=True)
    model = models.ForeignKey(Engine_model,verbose_name=('Engine model name'),related_name='model', on_delete=models.CASCADE, null= True)
    def __str__(self):
        return self.name
      

class model(models.Model):
    name = models.CharField(max_length=50)
    images = models.ImageField(null=True,blank=True, storage=fs)
    Brand = models.ForeignKey(brand, related_name='models', on_delete=models.CASCADE, null=True)
    Engine = models.OneToOneField(engine, related_name='model_model', on_delete=models.CASCADE, null=True)  # Change the related name here
    Features = models.ManyToManyField(feature, related_name='models')
    
    def __str__(self):
        return self.name

class car(models.Model):
    model =models.ForeignKey(model, on_delete=models.CASCADE , null = True)
    Chasis_no = models.CharField(max_length=50 , primary_key=True)
    
    def __str__(self):
        return self.Chasis_no
       

 

Showroom/views.py
from django.shortcuts import render
from .models import *

def brand_list(request):
    brands = brand.objects.all()
    return render(request, "Showroom/brand_list.html", {'brands': brands})

def brand_detail(request, profile_id):
    
        brandss = brand.objects.get(id=profile_id)
        models = brandss.models.all()
        

        return render(request, "Showroom/brand_detail.html", {'brandss': brandss, "models": models })

def our_team(request):
    team=staff.objects.all()
    return render(request , "Showroom/our_team.html",{'team':team})

def showroomss(request):
    Showroom=showroom.objects.all()
    return render(request ,  "Showroom/Showrooms.html", {'Showroom': Showroom})

Showroom/templates/Showroom/Showrooms.html
{% extends 'Showroom/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5" style="text-align: center;">
    
    {% if Showroom %}
    
        {% for showroom in Showroom %}
        <img src="{{ showroom.image.url }}" class="card-img" alt="Profile picture" height="530" >
        <br>
        <br>
        <h3><b>{{ showroom.name }}</b> Details</h3>
        
        <br>
        <hr>
        <p><strong>Location:</strong> {{ showroom.Location }}</p>
        <p><strong>Owner:</strong> {{ showroom.Owner }}</p>
        <p><strong>Contact : </strong> {{ showroom.contact }}</p>
        <p><strong>Our Staff:</strong></p>
        <ul>
            {% for staff_member in showroom.Staff.all %}
            <img src="{{ staff_member.image.url }}" class=#alt="Profile picture" height="230",width ='150px' >
            <li>{{ staff_member.name }} - <b> The {{ staff_member.Role }}</b></li>
            <hr>
            <br>
            <br>
            <br>
            <br>
            {% endfor %}
        </ul>
        {% endfor %}
    {% else %}
        <p>No showrooms found.</p>
    {% endif %}
</div>
{% endblock %}

Showroom/templates/Showroom/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags and title -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">

    <title> {% block title %}base{% endblock title %} </title>
</head>
<body>
    {% include 'Showroom/header.html' %}
    
    <div class="container mt-5 mb-5"> <!-- Add a container to wrap the content -->
        {% block content %}{% endblock %}
    </div>

    {% include 'Showroom/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Showroom/templates/Showroom/brand_detail.html
{% extends 'Showroom/base.html' %}
{% load static %}
{% block content %}


<div class="container mt-5" style="text-align: center;">
    {% if brandss %}
    <h3><b>{{ brandss.name }}'s</b> different Models</h3>
    <br>
    <br>
    <style>
        /* Add some margin between the cards */
        .card-gap {
            margin-bottom: 45 px;
        }
    </style>

    <div class="row" >


        {% for modelss in models %}
        <h3><b>{{ modelss.name }}</b></h3>
        <div class="col-md-8 offset-md-2 card-gap ">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        {% if modelss.images %}
                        <img src="{{ modelss.images.url }}" class="card-img" alt="Profile picture" height="330" >
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Model name: {{ modelss.name }}</h5>
                            <p class="card-text"><small class="text-muted">{{ brandss.showrooms.Owner }}</small></p>
                            
                            <p class="card-text">
                                <strong>Brand:</strong> {{ modelss.Brand.name }}<br>
                                {% if modelss.Engine %}
                                <strong>Engine:</strong> {{ modelss.Engine.name }}<br>
                                <strong>Engine Number:</strong> {{ modelss.Engine.Engine_no }}<br>

                                {% endif %}
                                            
                                <ul>
                                    <strong>Features:</strong>
                                    {% for feature in modelss.Features.all %}
                                        <li>{{ feature.name }}</li>
                                    {% endfor %}
                                </ul>
                                <strong>Available at:  </strong><a href="./Showrooms.html">'{{ brandss.showrooms.name }}'</a><br>
                            </p>
                            <a href="{% url 'Showroom:brand_list' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Brand not found.</p>
    {% endif %}
</div>

{% endblock %}

Showroom/templates/Showroom/brand_list.html
{% extends 'Showroom/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5" style ="text-align: center;">
    <h1>Welcome to your Showroom</h1>
    
</div>
<div class="container" style ="text-align: center;">
    <h3>Our Brands</h3>
    <div class="row">
        {% for brand in brands  %}
        <div class="col-md-3">
            <div class="card ">
                <img class="card-img-top" src="{{brand.Logo.url}}" alt="Profile picture"  height="250">
                <div class="card-body">
                    <h5 class="card-title">{{brand.name}}</h5>
                    <a href="{% url 'Showroom:brand_detail' brand.id %}" class="btn btn-primary" >View Profile</a>
                </div>
            </div>
            <p></p>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}

Showroom/templates/Showroom/footer.html
{% block content %}
<footer class="footer bg-dark mt-11 fixed-bottom text-center" style = "color:white">
    <div class="container" 
      <span class="text-center d-block">© 2023 Showroom App</span>
      <span class="text-center d-block">All rights reserved by Showroom.com lets get your dream car</span>
      
    </div>
  </footer>
{% endblock %}

Showroom/templates/Showroom/header.html
{% block content %}
<!-- header.html -->

<!-- Bootstrap navbar -->
<nav class="navbar navbar-dark bg-dark " style="min-height: 90px">
    <div class="container-fluid">
        <a class="navbar-brand "  href="#">Showroom website</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Find your dream Car here</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'Showroom:brand_list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Showroom:our_team' %}">Our team</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Brands
                        </a>
                        
                        <ul class="dropdown-menu dropdown-menu-dark">
                            
                            <li><a class="dropdown-item" href="{% url 'Showroom:brand_list' %}">Honda</a></li>
                            <li><a class="dropdown-item" href="{% url 'Showroom:brand_list' %}">Toyota</a></li>
                            <li><a class="dropdown-item" href="{% url 'Showroom:brand_list' %}">Ford</a></li>
                            <li><a class="dropdown-item" href="{% url 'Showroom:brand_list' %}">Tesla</a></li>
                            <li>
                        
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">back</a></li>
                        </ul>
                        
                    </li>
                </ul>
                <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>

<!-- Add your page content below -->

{% endblock %}

Showroom/templates/Showroom/our_team.html
{% extends 'Showroom/base.html' %}
{% load static %}
{% block content %}
<div class="container" style ="text-align: center;">
    <h3>Our Team</h3>
    <div class="row">
        {% for staff in team %}
        <div class="col-md-3">
            <div class="card ">
                <img class="card-img-top" src="{{staff.image.url}}" alt="Profile picture"  height="250">
                <div class="card-body">
                    <h5 class="card-title">{{staff.name}}</h5>
                    <h6 class="card-title">{{staff.name}} is our <b>'{{staff.Role}}'</b></h6>
                    {% if Showroom %}
                    <h6 class="card-title">{{staff.name}} works in <b>'{{ Showroom.name }}'</b></h6>
                    {% endif %}
                </div>
            </div>
            <p></p>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}